/* AUTOGENERATED DO NOT MODIFY */

/**
  ******************************************************************************
  * @file    network.c
  * @brief   NN Code autogenerated DO NOT MODIFY IT
  ******************************************************************************
  * @attention
  *
  * Copyright (c) 2023 STMicroelectronics.
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  *
  ******************************************************************************
  */

/*
 * GIT_SHA         "6770925d2803cfc24528c45bb3ba8b791b2a83e4"
 * GIT_BRANCH      "STAI-4.0"
 * GIT_DESCRIPTION "atonn-v1.1.3-275-g6770925d"
 *
 * Command Line options:
 * --load-mdesc-file = "/app/stm32ai/Utilities/configs/stm32n6"
 * --load-cdesc-file = "/app/stm32ai/Utilities/configs/cortex-m55"
 * --load-mpool-file = "/app/stm32ai/Utilities/linux/targets/stm32/resources/NPU/STM32N6xx/stm32n6"
 * --cache-maintenance = true
 * --enable-virtual-mem-pools = true
 * --native-float = true
 * --json-quant-file = "/tmp/stm32ai_service/2ab40949-5f8c-47b6-a46e-0fafdda0fce8/output/mnist_cnn_32x321_PerChannel_quant_mnist_calib (1)_npz_1_OE_3_3_1_Q.json"
 * --optimization = 3
 * --Os = true
 * --Omax-ca-pipe = 4
 * --Ocache-opt = true
 * --enable-epoch-controller = true
 * --output-info-file = "c_info"
 * --onnx-input = "/tmp/stm32ai_service/2ab40949-5f8c-47b6-a46e-0fafdda0fce8/output/mnist_cnn_32x321_PerChannel_quant_mnist_calib (1)_npz_1_OE_3_3_1.onnx"
 * --out-dir-prefix = "/tmp/stm32ai_service/2ab40949-5f8c-47b6-a46e-0fafdda0fce8/workspace/neural_art__network/"
 * --network-name = "network"
 * --generate-stai = true
 * --Oauto-sched = true
 *
 * auto* option expanded into:
 *   alt-scheduler = false
 */

#include "ll_aton_NN_interface.h"
#include "ll_aton.h"
#include "ll_aton_lib.h"
#include "ll_aton_version.h"
#include "ll_sw.h"
#include "ecloader.h"
#include "ll_aton_cipher.h"

/* Version check relaxed: generated with 1.1.3-275, library is 1.1.3-262 (same ABI) */
#if LL_ATON_VERSION_MAJOR != 1 || LL_ATON_VERSION_MINOR != 1 || LL_ATON_VERSION_MICRO != 3
#  error "Possible mismatch in ll_aton library used"
#endif

#if !defined(LL_ATON_DBG_BUFFER_INFO_EXCLUDED)
#  define LL_ATON_DBG_BUFFER_INFO_EXCLUDED 0
#endif

/* global pool 8 is 27.63 KB */
/* index=8 file postfix=xSPI2 name=octoFlash offset=0x71000000  absolute_mode size=117440504 READ_ONLY THROUGHPUT=MID LATENCY=HIGH byte width=1 freq ratio=6 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=ON read_power=110 write_power=400 use4initializers=YES score=50  */
/* global pool 7 is ? */
/* index=7 file postfix=xSPI1 name=hyperRAM offset=0x90000000  absolute_mode size=33554424 READ_WRITE THROUGHPUT=MID LATENCY=HIGH byte width=2 freq ratio=5 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=ON read_power=380 write_power=340 use4initializers=YES score=82  */
/* global pool 1 is 7.00 KB */
/* index=1 file postfix=AXISRAM5 name=npuRAM5 offset=0x342e0000  absolute_mode size=458752 READ_WRITE THROUGHPUT=HIGH LATENCY=LOW byte width=8 freq ratio=1.25 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=OFF read_power=18.531 write_power=16.201 use4initializers=NO score=94  */
/* global pool 2 is ? */
/* index=2 file postfix=AXISRAM4 name=npuRAM4 offset=0x34270000  absolute_mode size=458752 READ_WRITE THROUGHPUT=HIGH LATENCY=LOW byte width=8 freq ratio=1.25 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=OFF read_power=18.531 write_power=16.201 use4initializers=NO score=94  */
/* global pool 3 is ? */
/* index=3 file postfix=AXISRAM3 name=npuRAM3 offset=0x34200000  absolute_mode size=458752 READ_WRITE THROUGHPUT=HIGH LATENCY=LOW byte width=8 freq ratio=1.25 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=OFF read_power=18.531 write_power=16.201 use4initializers=NO score=94  */
/* global pool 0 is ? */
/* index=0 file postfix=AXISRAM6 name=npuRAM6 offset=0x34350000  absolute_mode size=458744 READ_WRITE THROUGHPUT=HIGH LATENCY=LOW byte width=8 freq ratio=1.25 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=OFF read_power=19.006 write_power=15.79 use4initializers=NO score=94  */
/* global pool 11 is 1.88 MB */
/* index=11 file postfix=AXISRAM2_AXISRAM3_AXISRAM4_AXISRAM5_AXISRAM6 name=cpuRAM2_npuRAM3_npuRAM4_npuRAM5_npuRAM6 offset=0x34100000  absolute_mode size=2883576 vpool READ_WRITE THROUGHPUT=HIGH LATENCY=MID byte width=8 freq ratio=1.25 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=OFF read_power=19.006 write_power=16.201 use4initializers=NO score=91  */
/* global pool 4 is ? */
/* index=4 file postfix=AXISRAM2 name=cpuRAM2 offset=0x34100000  absolute_mode size=1048576 READ_WRITE THROUGHPUT=MID LATENCY=MID byte width=8 freq ratio=2.5 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=OFF read_power=17.324 write_power=15.321 use4initializers=NO score=84  */
/* global pool 5 is ? */
/* index=5 file postfix=AXISRAM1 name=cpuRAM1 offset=0x34064000  absolute_mode size=0 READ_WRITE THROUGHPUT=MID LATENCY=MID byte width=8 freq ratio=2.5 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=OFF read_power=16.616 write_power=14.522 use4initializers=NO score=84  */
/* global pool 6 is ? */
/* index=6 file postfix=AXIFLEXMEM name=flexMEM offset=0x34000000  absolute_mode size=0 READ_WRITE THROUGHPUT=MID LATENCY=MID byte width=8 freq ratio=2.5 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=OFF read_power=9.381 write_power=8.569 use4initializers=NO score=84  */


const LL_Streng_EncryptionTypedef *LL_ATON_WeightEncryption_Info_network()
{
  static const LL_Streng_EncryptionTypedef LL_Streng_EncryptionStruct = {
    .enable = 0,
  };

  return &LL_Streng_EncryptionStruct;
}

const LL_Streng_EncryptionTypedef *LL_ATON_BlobEncryption_Info_network()
{
  static const LL_Streng_EncryptionTypedef LL_Streng_EncryptionStruct = {
    .enable = 0,
  };

  return &LL_Streng_EncryptionStruct;
}

LL_ATON_User_IO_Result_t LL_ATON_Set_User_Input_Buffer_network(uint32_t num, void* buffer, uint32_t size)
{
  LL_ATON_LIB_UNUSED(num);
  LL_ATON_LIB_UNUSED(buffer);
  LL_ATON_LIB_UNUSED(size);

  { 
    return LL_ATON_User_IO_WRONG_INDEX;
  }
}

void *LL_ATON_Get_User_Input_Buffer_network(uint32_t num)
{
  LL_ATON_LIB_UNUSED(num);

  { 
    return NULL;
  }
}

LL_ATON_User_IO_Result_t LL_ATON_Set_User_Output_Buffer_network(uint32_t num, void* buffer, uint32_t size)
{
  LL_ATON_LIB_UNUSED(num);
  LL_ATON_LIB_UNUSED(buffer);
  LL_ATON_LIB_UNUSED(size);

  { 
    return LL_ATON_User_IO_WRONG_INDEX;
  }
}

void *LL_ATON_Get_User_Output_Buffer_network(uint32_t num)
{
  LL_ATON_LIB_UNUSED(num);

  { 
    return NULL;
  }
}

#include "network_ecblobs.h"

/* scheduling epoch=0    nodes=26  ------------------------------------------------------------------- */

// Epoch Controller Blob (name='_ec_blob_network_1') micro instructions needed

// Epoch Controller Blob (name='_ec_blob_network_1') start function
static void _ec_blob_cache_start_func_1(const LL_ATON_RT_EpochBlockItem_t *epoch_block, const NN_Instance_TypeDef *nn_instance) {
  LL_ATON_LIB_UNUSED(epoch_block);
  LL_ATON_LIB_UNUSED(nn_instance);

  /* *** MCU cache invalidate (only) operation (HW, whole range) *** */
  /*     memory pool: 1 */
  /*     start: ((uintptr_t)(ATON_LIB_PHYSICAL_TO_VIRTUAL_ADDR(0x342e0000UL + 512))) */
  /*     end:   ((uintptr_t)(ATON_LIB_PHYSICAL_TO_VIRTUAL_ADDR(0x342e0000UL + 544))) */
  LL_ATON_Cache_MCU_Invalidate_Range(((uintptr_t)(ATON_LIB_PHYSICAL_TO_VIRTUAL_ADDR(0x342e0000UL + 512))) /* Equivalent hex address = 0x342e0200UL */, 32);

};


/* scheduling epoch=8    nodes=1   ------------------------------------------------------------------- */


static void LL_ATON_End_EpochBlock_8(const LL_ATON_RT_EpochBlockItem_t *epoch_block, const NN_Instance_TypeDef *nn_instance)
{
  LL_ATON_LIB_UNUSED(epoch_block);
  LL_ATON_LIB_UNUSED(nn_instance);

  /* *** MCU cache invalidate (only) operation for unaligned buffer end address (last line) *** */
  /*     memory pool: 1 */
  /*     start: ((uintptr_t)(ATON_LIB_PHYSICAL_TO_VIRTUAL_ADDR(0x342e0000UL + 512))) */
  /*     end:   ((uintptr_t)(ATON_LIB_PHYSICAL_TO_VIRTUAL_ADDR(0x342e0000UL + 544))) */
  LL_ATON_Cache_MCU_Invalidate_Range(((uintptr_t)(ATON_LIB_PHYSICAL_TO_VIRTUAL_ADDR(0x342e0000UL + 512))) /* Equivalent hex address = 0x342e0200UL */, 32);


/* Unit= 27 [PROCESSOR 0] */
/* kind=Softmax node=Softmax_24 */
  Softmax_integer_sw_info softmax_integer1_sw_info = {
    /* "general.input" tensor-related info: */
    .general.input.dim.tensor_b = 1,
    .general.input.dim.tensor_h = 1,
    .general.input.dim.tensor_w = 10,
    .general.input.dim.tensor_c = 1,
    .general.input.dim.num_elem = 10,
    .general.input.stride.b = 10,
    .general.input.stride.h = 10,
    .general.input.stride.w = 1,
    .general.input.stride.c = 1,
    .general.input.mem.start_offset = ((unsigned char *)(ATON_LIB_PHYSICAL_TO_VIRTUAL_ADDR(0x342e0000UL + 528))) /* Equivalent hex address = 0x342e0210UL */,
    .general.input.format.is_signed = 1,
    /* "is" tensor-related info: */
    .is.mem.start_offset = ((unsigned char *)(ATON_LIB_PHYSICAL_TO_VIRTUAL_ADDR(0x71000000UL + 28240))) /* Equivalent hex address = 0x71006e50UL */,
    .is.format.is_signed = 0,
    .is.dim.num_elem = 1,
    /* "izp" tensor-related info: */
    .izp.mem.start_offset = ((unsigned char *)(ATON_LIB_PHYSICAL_TO_VIRTUAL_ADDR(0x71000000UL + 28272))) /* Equivalent hex address = 0x71006e70UL */,
    .izp.format.is_signed = 1,
    .izp.dim.num_elem = 1,
    /* "os" tensor-related info: */
    .os.mem.start_offset = ((unsigned char *)(ATON_LIB_PHYSICAL_TO_VIRTUAL_ADDR(0x71000000UL + 28256))) /* Equivalent hex address = 0x71006e60UL */,
    .os.format.is_signed = 0,
    .os.dim.num_elem = 1,
    /* "ozp" tensor-related info: */
    .ozp.mem.start_offset = ((unsigned char *)(ATON_LIB_PHYSICAL_TO_VIRTUAL_ADDR(0x71000000UL + 28288))) /* Equivalent hex address = 0x71006e80UL */,
    .ozp.format.is_signed = 1,
    .ozp.dim.num_elem = 1,
    /* "scratch" tensor-related info: */
    .scratch.dim.tensor_b = 1,
    .scratch.dim.tensor_h = 1,
    .scratch.dim.tensor_w = 125,
    .scratch.dim.tensor_c = 1,
    .scratch.dim.num_elem = 125,
    .scratch.stride.b = 500,
    .scratch.stride.h = 500,
    .scratch.stride.w = 4,
    .scratch.stride.c = 4,
    .scratch.mem.start_offset = ((unsigned char *)(ATON_LIB_PHYSICAL_TO_VIRTUAL_ADDR(0x342e0000UL + 0))) /* Equivalent hex address = 0x342e0000UL */,
    .scratch.format.is_signed = 1,
    /* "general.output" tensor-related info: */
    .general.output.dim.tensor_b = 1,
    .general.output.dim.tensor_h = 1,
    .general.output.dim.tensor_w = 10,
    .general.output.dim.tensor_c = 1,
    .general.output.dim.num_elem = 10,
    .general.output.stride.b = 10,
    .general.output.stride.h = 10,
    .general.output.stride.w = 1,
    .general.output.stride.c = 1,
    .general.output.mem.start_offset = ((unsigned char *)(ATON_LIB_PHYSICAL_TO_VIRTUAL_ADDR(0x342e0000UL + 512))) /* Equivalent hex address = 0x342e0200UL */,
    .general.output.format.is_signed = 1,
    /* Node-specific Hyper-parameters: */
    .quantized_multiplier = 1467558912,
    .left_shift = 24,
    .diff_min = -124,
    .axis = 3,
    .general.type = LL_SW_SOFTMAX,
  };

  /* Low Level SW Layer function invocation. This will exploit EmbedNets libs) */
  /* Node Softmax_24 mapped on EmbedNets (INTEGER) as Softmax | Category: Computational */
  ll_sw_forward_softmax_integer(&softmax_integer1_sw_info);
  /* *** MCU cache clean (only) operation (SW, whole range) *** */
  /*     memory pool: 1 */
  /*     start: ((uintptr_t)(ATON_LIB_PHYSICAL_TO_VIRTUAL_ADDR(0x342e0000UL + 0))) */
  /*     end:   ((uintptr_t)(ATON_LIB_PHYSICAL_TO_VIRTUAL_ADDR(0x342e0000UL + 544))) */
  LL_ATON_Cache_MCU_Clean_Range(((uintptr_t)(ATON_LIB_PHYSICAL_TO_VIRTUAL_ADDR(0x342e0000UL + 0))) /* Equivalent hex address = 0x342e0000UL */, 544);


}

/* scheduling epoch=9    nodes=1   ------------------------------------------------------------------- */

/* scheduling DONE                 ------------------------------------------------------------------- */

const LL_ATON_RT_EpochBlockItem_t *LL_ATON_EpochBlockItems_network(void) {

  static const LL_ATON_RT_EpochBlockItem_t ll_atonn_rt_epoch_block_array[] = {
    {
      .start_epoch_block = _ec_blob_cache_start_func_1,
      .end_epoch_block = NULL,
      .blob_address = (uintptr_t)(_ec_blob_network_1_address),
      .wait_mask = 0,
      .flags = EpochBlock_Flags_epoch_start | EpochBlock_Flags_epoch_end | EpochBlock_Flags_blob | EpochBlock_Flags_pure_hw,
#ifdef LL_ATON_EB_DBG_INFO
      .epoch_num = 1,
      .last_epoch_num = 7,
      .estimated_npu_cycles = 47660,
      .estimated_tot_cycles = 186112,
#endif // LL_ATON_EB_DBG_INFO
    },
    {
      .start_epoch_block = NULL,
      .end_epoch_block = LL_ATON_End_EpochBlock_8,
      .wait_mask = 0x00000000,
      .flags = EpochBlock_Flags_epoch_start | EpochBlock_Flags_epoch_end | EpochBlock_Flags_pure_sw,
#ifdef LL_ATON_EB_DBG_INFO
      .epoch_num = 8,
      .last_epoch_num = 8,
      .in_streng_mask = 0x00000000,
      .out_streng_mask = 0x00000000,
      .estimated_npu_cycles = 274,
      .estimated_tot_cycles = 274,
#endif // LL_ATON_EB_DBG_INFO
    },
    {
      .flags = EpochBlock_Flags_last_eb,
    },
  };


  return ll_atonn_rt_epoch_block_array;
}

const LL_Buffer_InfoTypeDef *LL_ATON_Input_Buffers_Info_network(void)
{
  static const uint32_t buff_info__shape_1_32_32_3[] = { 1, 32, 3, 32 };
  static const uint32_t buff_info__mem_shape_F_1_32_32_3[] = { 1, 32, 32, 3 };
  static const float buff_info_Input_0_out_0_quant_scale[] = { 0.00392156885936856 };
  static const int16_t buff_info_Input_0_out_0_quant_offset[] = { -128 };
#if LL_ATON_DBG_BUFFER_INFO_EXCLUDED == 0
  static const uint32_t buff_info__shape_16_3_3_3[] = { 16, 3, 3, 3 };
  static const uint32_t buff_info__mem_shape_L_16_3_3_3[] = { 16, 3, 3, 3 };
  static const float buff_info_Conv2D_3_weights_quant_scale[] = { 0.0044748461805284, 0.0027427151799202, 0.00528654875233769, 0.00324298557825387, 0.00420867837965488, 0.00342333479784429, 0.00144634756725281, 0.00390830915421247, 0.00206503318622708, 0.00293564423918724, 0.0071716895326972, 0.00153959239833057, 0.00455912109464407, 0.00254664290696383, 0.00237513636238873, 0.00244860094971955 };
  static const int16_t buff_info_Conv2D_3_weights_quant_offset[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
  static const uint32_t buff_info__shape_32_16_3_3[] = { 32, 3, 3, 16 };
  static const uint32_t buff_info__mem_shape_M8_32_16_3_3[] = { 32, 2, 3, 3, 8 };
  static const float buff_info_Conv2D_8_weights_quant_scale[] = { 0.0025392509996891, 0.00344376964494586, 0.00541131198406219, 0.00225443765521049, 0.0026921103708446, 0.0082045691087842, 0.00266447081230581, 0.00366183067671955, 0.00370504334568977, 0.0029291391838342, 0.00209855637513101, 0.0022520087659359, 0.00326003832742572, 0.00334030436351895, 0.00403097737580538, 0.00272794254124165, 0.00241112732328475, 0.00710918428376317, 0.00462629459798336, 0.00234392052516341, 0.00788854341953993, 0.006156993098557, 0.00304043781943619, 0.00341267581097782, 0.00258889142423868, 0.0024462363217026, 0.00486243655905128, 0.00400244630873203, 0.00249025132507086, 0.00512684788554907, 0.00372798601165414, 0.00261896080337465 };
  static const int16_t buff_info_Conv2D_8_weights_quant_offset[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
  static const uint32_t buff_info__shape_64_32_3_3[] = { 64, 3, 3, 32 };
  static const uint32_t buff_info__mem_shape_M8_64_32_3_3[] = { 64, 4, 3, 3, 8 };
  static const float buff_info_Conv2D_13_weights_quant_scale[] = { 0.00308519625104964, 0.00388265587389469, 0.00286223948933184, 0.00176120141986758, 0.00877500791102648, 0.00503010675311089, 0.00312251201830804, 0.0077988775447011, 0.00136459525674582, 0.00594074698165059, 0.00700563471764326, 0.00187744316644967, 0.00421400228515267, 0.00593042699620128, 0.00453763734549284, 0.00209668255411088, 0.00318054482340813, 0.00407297629863024, 0.00409695785492659, 0.0031968611292541, 0.00544052058830857, 0.00557793769985437, 0.0052788401953876, 0.00456516025587916, 0.00533436238765717, 0.00166415516287088, 0.0058895368129015, 0.00342853716574609, 0.00190531299449503, 0.00908474158495665, 0.00581979192793369, 0.00454224599525332, 0.00361204473301768, 0.00363350124098361, 0.00780084589496255, 0.00362940249033272, 0.000783560331910849, 0.00245054671540856, 0.00123738509137183, 0.00168729771394283, 0.00549371587112546, 0.00208677700720727, 0.0112351728603244, 0.00216082436963916, 0.00816127099096775, 0.00381820858456194, 0.00118337653111666, 0.00366037362255156, 0.00459165126085281, 0.00715451734140515, 0.00765208387747407, 0.00230961805209517, 0.00167696131393313, 0.00241474597714841, 0.00296534621156752, 0.00186238903552294, 0.00717259524390101, 0.00689423503354192, 0.00679499935358763, 0.00288984505459666, 0.00195551244542003, 0.00421215500682592, 0.0042514898814261, 0.00186417065560818 };
  static const int16_t buff_info_Conv2D_13_weights_quant_offset[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
  static const uint32_t buff_info__shape_64_64_1_1[] = { 64, 1, 1, 64 };
  static const uint32_t buff_info__mem_shape_F_64_64_1_1[] = { 64, 64, 1, 1 };
  static const float buff_info_Gemm_18_weights_transposed_3_quant_scale[] = { 0.00408888328820467, 0.00251935026608407, 0.00306309317238629, 0.00402950262650847, 0.00371521199122071, 0.00300742033869028, 0.00439287815243006, 0.00440107751637697, 0.00200598384253681, 0.00190540112089366, 0.00223615136928856, 0.00401763850823045, 0.00294473161920905, 0.00206392700783908, 0.0055667064152658, 0.00192139518912882, 0.00177012267522514, 0.00315983174368739, 0.00473549263551831, 0.00384156894870102, 0.00374408368952572, 0.00196224707178771, 0.00367320980876684, 0.00186928710900247, 0.00339233735576272, 0.00274021527729928, 0.00316008785739541, 0.00192195398267359, 0.0029208620544523, 0.00192486844025552, 0.00381379597820342, 0.00182676676195115, 0.00363689544610679, 0.00310616125352681, 0.001850800588727, 0.00291719613596797, 0.00170180841814727, 0.00206664646975696, 0.00401095021516085, 0.00181546900421381, 0.00299448356963694, 0.00173833162989467, 0.00335926143452525, 0.00267713097855449, 0.00341963185928762, 0.00181465619243681, 0.00442248536273837, 0.00394706521183252, 0.00169564154930413, 0.00351649266667664, 0.00545630464330316, 0.00428237719461322, 0.0038151852786541, 0.00173752137925476, 0.00195932551287115, 0.00348088820464909, 0.00327500957064331, 0.00378716015256941, 0.00373897142708302, 0.00345702958293259, 0.0055057262070477, 0.00169464398641139, 0.00372663210146129, 0.00193029665388167 };
  static const int16_t buff_info_Gemm_18_weights_transposed_3_quant_offset[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
  static const uint32_t buff_info__shape_10_64_1_1[] = { 10, 1, 1, 64 };
  static const uint32_t buff_info__mem_shape_F_10_64_1_1[] = { 10, 64, 1, 1 };
  static const float buff_info_Gemm_21_weights_transposed_9_quant_scale[] = { 0.00747792236506939, 0.0058902483433485, 0.00369483814574778, 0.00460628140717745, 0.00449909642338753, 0.00341583462432027, 0.00494425045326352, 0.00396303040906787, 0.00580473756417632, 0.00460091140121222 };
  static const int16_t buff_info_Gemm_21_weights_transposed_9_quant_offset[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
  static const uint32_t buff_info__shape_1[] = { 1, 1, 1, 1 };
  static const uint32_t buff_info__mem_shape_U_1[] = { 1 };
#endif // LL_ATON_DBG_BUFFER_INFO_EXCLUDED == 0
  static const LL_Buffer_InfoTypeDef buff_info[] = {
    {
      .name = "Input_0_out_0",
      .addr_base = {(unsigned char *)(0x342e0000UL) /* Equivalent hex address = 0x342e0000UL */},
      .offset_start = 0,
      .offset_end = 3072,
      .offset_limit = 3136,
      .is_user_allocated = 0,
      .is_param = 0,
      .epoch = 0,
      .batch = 1,
      .mem_shape = buff_info__mem_shape_F_1_32_32_3,
      .mem_ndims = 4,
      .chpos = CHPos_First,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_1_32_32_3,
      .per_channel = 0,
      .scale = buff_info_Input_0_out_0_quant_scale,
      .offset = buff_info_Input_0_out_0_quant_offset,
    },
#if LL_ATON_DBG_BUFFER_INFO_EXCLUDED == 0
    {
      .name = "Conv2D_3_weights",
      .addr_base = {(unsigned char *)(0x71000000UL) /* Equivalent hex address = 0x71000000UL */},
      .offset_start = 27808,
      .offset_end = 28240,
      .offset_limit = 28304,
      .is_user_allocated = 0,
      .is_param = 1,
      .epoch = 0,
      .batch = 3,
      .mem_shape = buff_info__mem_shape_L_16_3_3_3,
      .mem_ndims = 4,
      .chpos = CHPos_Last,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_16_3_3_3,
      .per_channel = 1,
      .scale = buff_info_Conv2D_3_weights_quant_scale,
      .offset = buff_info_Conv2D_3_weights_quant_offset,
    },
    {
      .name = "Conv2D_8_weights",
      .addr_base = {(unsigned char *)(0x71000000UL) /* Equivalent hex address = 0x71000000UL */},
      .offset_start = 18432,
      .offset_end = 23040,
      .offset_limit = 23104,
      .is_user_allocated = 0,
      .is_param = 1,
      .epoch = 0,
      .batch = 8,
      .mem_shape = buff_info__mem_shape_M8_32_16_3_3,
      .mem_ndims = 5,
      .chpos = CHPos_Mixed,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_32_16_3_3,
      .per_channel = 1,
      .scale = buff_info_Conv2D_8_weights_quant_scale,
      .offset = buff_info_Conv2D_8_weights_quant_offset,
    },
    {
      .name = "Conv2D_13_weights",
      .addr_base = {(unsigned char *)(0x71000000UL) /* Equivalent hex address = 0x71000000UL */},
      .offset_start = 0,
      .offset_end = 18432,
      .offset_limit = 18496,
      .is_user_allocated = 0,
      .is_param = 1,
      .epoch = 0,
      .batch = 8,
      .mem_shape = buff_info__mem_shape_M8_64_32_3_3,
      .mem_ndims = 5,
      .chpos = CHPos_Mixed,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_64_32_3_3,
      .per_channel = 1,
      .scale = buff_info_Conv2D_13_weights_quant_scale,
      .offset = buff_info_Conv2D_13_weights_quant_offset,
    },
    {
      .name = "Gemm_18_weights_transposed_3",
      .addr_base = {(unsigned char *)(0x71000000UL) /* Equivalent hex address = 0x71000000UL */},
      .offset_start = 23040,
      .offset_end = 27144,
      .offset_limit = 27208,
      .is_user_allocated = 0,
      .is_param = 1,
      .epoch = 0,
      .batch = 64,
      .mem_shape = buff_info__mem_shape_F_64_64_1_1,
      .mem_ndims = 4,
      .chpos = CHPos_First,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_64_64_1_1,
      .per_channel = 1,
      .scale = buff_info_Gemm_18_weights_transposed_3_quant_scale,
      .offset = buff_info_Gemm_18_weights_transposed_3_quant_offset,
    },
    {
      .name = "Gemm_21_weights_transposed_9",
      .addr_base = {(unsigned char *)(0x71000000UL) /* Equivalent hex address = 0x71000000UL */},
      .offset_start = 27152,
      .offset_end = 27794,
      .offset_limit = 27864,
      .is_user_allocated = 0,
      .is_param = 1,
      .epoch = 0,
      .batch = 64,
      .mem_shape = buff_info__mem_shape_F_10_64_1_1,
      .mem_ndims = 4,
      .chpos = CHPos_First,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_10_64_1_1,
      .per_channel = 1,
      .scale = buff_info_Gemm_21_weights_transposed_9_quant_scale,
      .offset = buff_info_Gemm_21_weights_transposed_9_quant_offset,
    },
    {
      .name = "Gemm_21_squeeze_y_11_148_atonn_internal_scale",
      .addr_base = {(unsigned char *)(0x71000000UL) /* Equivalent hex address = 0x71000000UL */},
      .offset_start = 28240,
      .offset_end = 28244,
      .offset_limit = 28312,
      .is_user_allocated = 0,
      .is_param = 1,
      .epoch = 0,
      .batch = 1,
      .mem_shape = buff_info__mem_shape_U_1,
      .mem_ndims = 1,
      .chpos = CHPos_UNDEFINED,
      .Qm = 0,
      .Qn = 0,
      .Qunsigned = 1,
      .type = DataType_FLOAT,
      .nbits = 32,
      .ndims = 4,
      .shape = buff_info__shape_1,
    },
    {
      .name = "Gemm_21_squeeze_y_11_148_atonn_internal_offset",
      .addr_base = {(unsigned char *)(0x71000000UL) /* Equivalent hex address = 0x71000000UL */},
      .offset_start = 28272,
      .offset_end = 28273,
      .offset_limit = 28344,
      .is_user_allocated = 0,
      .is_param = 1,
      .epoch = 0,
      .batch = 1,
      .mem_shape = buff_info__mem_shape_U_1,
      .mem_ndims = 1,
      .chpos = CHPos_UNDEFINED,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_FXP,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_1,
    },
    {
      .name = "Softmax_24_152_atonn_internal_scale",
      .addr_base = {(unsigned char *)(0x71000000UL) /* Equivalent hex address = 0x71000000UL */},
      .offset_start = 28256,
      .offset_end = 28260,
      .offset_limit = 28328,
      .is_user_allocated = 0,
      .is_param = 1,
      .epoch = 0,
      .batch = 1,
      .mem_shape = buff_info__mem_shape_U_1,
      .mem_ndims = 1,
      .chpos = CHPos_UNDEFINED,
      .Qm = 0,
      .Qn = 0,
      .Qunsigned = 1,
      .type = DataType_FLOAT,
      .nbits = 32,
      .ndims = 4,
      .shape = buff_info__shape_1,
    },
    {
      .name = "Softmax_24_152_atonn_internal_offset",
      .addr_base = {(unsigned char *)(0x71000000UL) /* Equivalent hex address = 0x71000000UL */},
      .offset_start = 28288,
      .offset_end = 28289,
      .offset_limit = 28360,
      .is_user_allocated = 0,
      .is_param = 1,
      .epoch = 0,
      .batch = 1,
      .mem_shape = buff_info__mem_shape_U_1,
      .mem_ndims = 1,
      .chpos = CHPos_UNDEFINED,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_FXP,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_1,
    },
#endif // LL_ATON_DBG_BUFFER_INFO_EXCLUDED == 0
    {
      .name = NULL,
    }
  };

  return buff_info;
}

const LL_Buffer_InfoTypeDef *LL_ATON_Output_Buffers_Info_network(void)
{
  static const uint32_t buff_info__shape_1_10[] = { 1, 1, 10, 1 };
  static const uint32_t buff_info__mem_shape_U_1_10[] = { 1, 10 };
  static const float buff_info_Quantize_25_out_0_quant_scale[] = { 0.00390625 };
  static const int16_t buff_info_Quantize_25_out_0_quant_offset[] = { -128 };
  static const LL_Buffer_InfoTypeDef buff_info[] = {
    {
      .name = "Quantize_25_out_0",
      .addr_base = {(unsigned char *)(0x342e0000UL) /* Equivalent hex address = 0x342e0000UL */},
      .offset_start = 512,
      .offset_end = 522,
      .offset_limit = 592,
      .is_user_allocated = 0,
      .is_param = 0,
      .epoch = 8,
      .batch = 1,
      .mem_shape = buff_info__mem_shape_U_1_10,
      .mem_ndims = 2,
      .chpos = CHPos_UNDEFINED,
      .Qm = 0,
      .Qn = 0,
      .Qunsigned = 1,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_1_10,
      .per_channel = 0,
      .scale = buff_info_Quantize_25_out_0_quant_scale,
      .offset = buff_info_Quantize_25_out_0_quant_offset,
    },
    {
      .name = NULL,
    }
  };

  return buff_info;
}

const LL_Buffer_InfoTypeDef *LL_ATON_Internal_Buffers_Info_network(void)
{
  return NULL;
}

