
/* AUTOGENERATED DO NOT MODIFY */

/**
 ******************************************************************************
 * @file    stai_network.h
 * @author  SRA Artificial Intelligence & Embedded Architectures
 * @brief   Implementation of ST.AI platform public APIs for ATON
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#ifndef __STAI_ATON_NETWORK_H
#define __STAI_ATON_NETWORK_H

// Include ATON runtime/library configuration file
#include "ll_aton_config.h"
#include "ll_aton_stai_internal.h"

// clang-format off
#ifdef __cplusplus
extern "C"
{
#endif

/*
 * NOTE: the beyond macro MUST be set to the same value when compiling the different ATON runtime/library, and
 *       AtoNN compiler generated files
 */
#if !defined(LL_ATON_DBG_BUFFER_INFO_EXCLUDED)
#define LL_ATON_DBG_BUFFER_INFO_EXCLUDED 0
#endif

// Derive alignment
#define _alignof(t)                                                                                                    \
  ((sizeof(t) > 1) ? offsetof(                                                                                         \
                         struct {                                                                                      \
                           char c;                                                                                     \
                           t x;                                                                                        \
                         },                                                                                            \
                         x)                                                                                            \
                   : 1)

// Include ST.AI headers
#include "stai_aton_common.h"

/*****************************************************************************/
#define STAI_NETWORK_CONTEXT_SIZE      ((stai_size)sizeof(_stai_aton_context))
#define STAI_NETWORK_CONTEXT_ALIGNMENT (_alignof(_stai_aton_context))

/*****************************************************************************/
STAI_API_DECLARE_BEGIN

/*****************************************************************************/
/* ST.AI API extensions are available */
#ifndef HAS_STAI_EXT
#define HAS_STAI_EXT
#endif // HAS_STAI_EXT

/*****************************************************************************/
/*  Network management APIs  */
STAI_API_ENTRY
stai_return_code stai_network_init(stai_network *network);

STAI_API_ENTRY
stai_return_code stai_network_deinit(stai_network *network);

STAI_API_ENTRY
stai_return_code stai_network_run(stai_network *network, const stai_run_mode mode);

STAI_API_ENTRY
stai_return_code stai_network_train(stai_network *network, const stai_run_mode mode);

/*****************************************************************************/
/*  Getters APIs  */

// needed only for python bindings to query internal context byte size
STAI_API_ENTRY
static inline stai_size stai_network_get_context_size(void)
{
  return STAI_NETWORK_CONTEXT_SIZE;
}

STAI_API_ENTRY
stai_return_code stai_network_get_info(stai_network *network, stai_network_info *info);

STAI_API_ENTRY
stai_return_code stai_network_get_inputs(stai_network *network, stai_ptr *inputs, stai_size *n_inputs);

STAI_API_ENTRY
stai_return_code stai_network_get_weights(stai_network *network, stai_ptr *weights, stai_size *n_weights);

STAI_API_ENTRY
stai_return_code stai_network_get_outputs(stai_network *network, stai_ptr *outputs, stai_size *n_outputs);

STAI_API_ENTRY
stai_return_code stai_network_get_activations(stai_network *network, stai_ptr *activations,
                                                            stai_size *n_activations);

STAI_API_ENTRY
stai_return_code stai_network_get_states(stai_network *network, stai_ptr *states, stai_size *n_states);
STAI_API_ENTRY
stai_return_code stai_network_get_error(stai_network *network);

/*****************************************************************************/
/*  Setters APIs  */

/**
 * @brief Set array of input buffers
 * @param network NN for which to set the input buffers
 * @param inputs array of input buffer pointers
 * @param n_inputs number of elements in the input buffer array
 * @return ST.AI error code
 *
 * @note for user allocatable buffers it is necessary that the effectively allocated memory comprises
 *       bottom & top paddings (where necessary) that allow for both the real buffer start address and the
 *       allocated size beyond this real start address to be aligned with the user buffer alignment macro
 *       (`STAI_CACHE_USER_BUFFER_ALIGNMENT`)
 */
STAI_API_ENTRY
stai_return_code stai_network_set_inputs(stai_network *network, const stai_ptr *inputs,
                                                       const stai_size n_inputs);

/**
 * @brief Set array of weight buffers
 * @param network NN for which to set the weight buffers
 * @param weights array of weight buffer pointers
 * @param n_weights number of elements in the weight buffer array
 * @return ST.AI error code
 *
 * @note user allocatable buffers are not supported for weights
 */
STAI_API_ENTRY
stai_return_code stai_network_set_weights(stai_network *network, const stai_ptr *weights,
                                                        const stai_size n_weights);

/**
 * @brief Set array of output buffers
 * @param network NN for which to set the output buffers
 * @param outputs array of output buffer pointers
 * @param n_outputs number of elements in the output buffer array
 * @return ST.AI error code
 *
 * @note for user allocatable buffers it is necessary that the effectively allocated memory comprises
 *       bottom & top paddings (where necessary) that allow for both the real buffer start address and the
 *       allocated size beyond this real start address to be aligned with the user buffer alignment macro
 *       (`STAI_CACHE_USER_BUFFER_ALIGNMENT`)
 */
STAI_API_ENTRY
stai_return_code stai_network_set_outputs(stai_network *network, const stai_ptr *outputs,
                                                        const stai_size n_outputs);

/**
 * @brief Set array of activation buffers
 * @param network NN for which to set the activation buffers
 * @param activations array of activation buffer pointers
 * @param n_activations number of elements in the activation buffer array
 * @return ST.AI error code
 *
 * @note user allocatable buffers are not supported for activations
 */
STAI_API_ENTRY
stai_return_code stai_network_set_activations(stai_network *network, const stai_ptr *activations,
                                                            const stai_size n_activations);

STAI_API_ENTRY
stai_return_code stai_network_set_states(stai_network *network, const stai_ptr *states,
                                                       const stai_size n_states);

STAI_API_ENTRY
stai_return_code stai_network_set_callback(stai_network *network, const stai_event_cb cb,
                                                         void *cb_cookie);

/***************************************************************************/
/*  Extended ATON Target Specific APIs  */

/** Asynchronous Execution **/
/**
 * @brief Continue network execution of an asynchronously started/run network
 *        (i.e. network was started/run in `stai_run_mode::STAI_MODE_ASYNC` mode)
 * @details Running a network in asynchronous mode (see function `stai_network_run()` and its
 *          parameter `mode` being equal to `stai_run_mode::STAI_MODE_ASYNC`) means that
 *          `stai_network_run()` returns while the network is still in execution. In this case
 *          the user may not call `stai_network_run()` again until the network's execution has
 *          actually finished.
 *          Therefore, we need to have two new API functions, one that provides the execution status of the
 *          network `stai_ext_network_get_nn_run_status()`,
 *          and one which triggers the continuation of the network execution
 *          `stai_ext_network_run_continue()`.
 * @details While the asynchronously started network is in execution the user may call any application specific code.
 *          When she/he has finished to do so she/he should call `stai_ext_network_get_nn_run_status()`
 *          and act as follows with respect to its different return values:
 *          - `STAI_RUNNING_NO_WFE`: network is still running and `stai_ext_network_run_continue()` must
 *            be called (without calling `stai_ext_wfe()` before)
 *          - `STAI_RUNNING_WFE`: network is still running and `stai_ext_wfe()` should be called before calling
 *            `stai_ext_network_run_continue()`.
 *            NOTE, that in this case no other network instance may be run/continued from within the same thread!
 *            It is entirely the user's responsibility to comply with this restriction!
 *          - `STAI_DONE`: network execution has finished (do NOT call `stai_ext_network_run_continue()`
 * again)
 * @param[in] network network opaque pointer
 * @return error or execution status (i.e. `STAI_RUNNING_NO_WFE`, `STAI_RUNNING_WFE`, or `STAI_DONE`) return value
 *
 * @note enum `stai_return_code` might need to be extended to better represent errors of new API functions,
 *       in this case e.g. an enum value specifying that the provided network handle does not identify the currently
 *       running network, and one that informs about a still running network execution (for function
 *       `stai_network_run()`).
 */
STAI_API_ENTRY
stai_return_code stai_ext_network_run_continue(stai_network *network);

/**
 * @brief Get execution status of a network
 * @details Running a network in asynchronous mode (see function `stai_network_run()` and its
 *          parameter `mode` being equal to `stai_run_mode::STAI_MODE_ASYNC`) means that
 *          `stai_network_run()` returns while the network is still in execution. In this case
 *          the user may not call `stai_network_run()` again until the network's execution has
 *          actually finish.
 *          Therefore, we need to have two new API functions, one that provides the execution status of the
 *          network `stai_ext_network_get_nn_run_status()`,
 *          and one which triggers the continuation of the network execution
 *          `stai_ext_network_run_continue()`.
 * @details While the asynchronously started network is in execution the user may call any application specific code.
 *          When she/he has finished to do so she/he should call `stai_ext_network_get_nn_run_status()`
 *          and act as follows with respect to its different return values:
 *          - `STAI_RUNNING_NO_WFE`: network is still running and `stai_ext_network_run_continue()` must
 *            be called (without calling `stai_ext_wfe()` before)
 *          - `STAI_RUNNING_WFE`: network is still running and `stai_ext_wfe()` should be called before calling
 *            `stai_ext_network_run_continue()`.
 *            NOTE, that in this case no other network instance may be run/continued from within the same thread!
 *            It is entirely the user's responsibility to comply with this restriction!
 *          - `STAI_DONE`: network execution has finished (do NOT call `stai_ext_network_run_continue()`
 * again)
 * @param[in] network network handle
 * @return error or execution status (i.e. `STAI_RUNNING_NO_WFE`, `STAI_RUNNING_WFE`, or `STAI_DONE`) return value
 *
 * @note enum `stai_return_code` might need to be extended to better represent errors of new API functions,
 *       in this case e.g. an enum value specifying that the provided network handle does not identify the currently
 *       running network, and one that informs about a still running network execution (for function
 *       `stai_network_run()`).
 */
STAI_API_ENTRY
stai_return_code stai_ext_network_get_nn_run_status(stai_network *network);

/**
 * @brief Prepare the network for a new inference
 * @details In case `stai_ext_network_get_nn_run_status()` returns either `STAI_DONE` or
 *          `STAI_RUNNING_NO_WFE` (when called by the thread which actually executes the inference of the passed
 *          `network`), prepare `network` for another/new inference run.
 * @param[in] network network handle
 * @return
 *
 * @note May only be called by the thread actually executing the inference of `network`!
 * @note Necessary only in case current inference is/has been executed asynchronously!
 */
STAI_API_ENTRY
stai_return_code stai_ext_network_new_inference(stai_network *network);

/*****************************************************************************/
STAI_API_DECLARE_END

/*****************************************************************************/
#define STAI_NETWORK_STATES_NUM  (0)
#define STAI_NETWORK_STATES_SIZE (0)

/*****************************************************************************/
/************************** SUBSTITUTABLE section ****************************/
/*****************************************************************************/

/**************************** Cache line size(s) *****************************/
#ifndef STAI_CACHE_MCU_LINESIZE
#define STAI_CACHE_MCU_LINESIZE (32)
#elif (STAI_CACHE_MCU_LINESIZE != 32)
#error "MCU cache line size mismatch"
#endif

/* NPU cache extension is available */
#ifndef STAI_EXT_CACHE_HAS_NPU
#define STAI_EXT_CACHE_HAS_NPU
#endif
#define STAI_NETWORK_EXT_CACHE_HAS_NPU

#ifndef STAI_EXT_CACHE_NPU_LINESIZE
#define STAI_EXT_CACHE_NPU_LINESIZE (64)
#elif (STAI_EXT_CACHE_NPU_LINESIZE != 64)
#error "NPU cache line size mismatch"
#endif

#ifndef STAI_CACHE_USER_BUFFER_ALIGNMENT
#define STAI_CACHE_USER_BUFFER_ALIGNMENT STAI_CACHE_MCU_LINESIZE  // NOTE: user allocated buffers are assumed not to be NPU cacheable!
#endif

/********************************** INPUTS ***********************************/
#define STAI_NETWORK_IN_NUM (1)
#define STAI_NETWORK_IN_ALIGNMENTS \
  { \
    32 \
  }
#define STAI_NETWORK_IN_NAMES \
  { \
    "Input_0_out_0" \
  }
#define STAI_NETWORK_IN_FORMATS \
  { \
    STAI_FORMAT_S8 \
  }
#define STAI_NETWORK_IN_SIZES \
  { \
    3072 \
  }
#define STAI_NETWORK_IN_SIZES_BYTES \
  { \
    3072 \
  }

#define STAI_NETWORK_IN_1_ALIGNMENT (32)
#define STAI_NETWORK_IN_1_NAME "Input_0_out_0"
#define STAI_NETWORK_IN_1_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_NETWORK_IN_1_FORMAT (STAI_FORMAT_S8)
#define STAI_NETWORK_IN_1_SIZE (3072)
#define STAI_NETWORK_IN_1_SIZE_BYTES (3072)
#define STAI_NETWORK_IN_1_CHANNEL (3)
#define STAI_NETWORK_IN_1_HEIGHT (32)
#define STAI_NETWORK_IN_1_WIDTH (32)
#define STAI_NETWORK_IN_1_BATCH (1)
#define STAI_NETWORK_IN_1_RANK (4)
#define STAI_NETWORK_IN_1_SHAPE \
  { \
    1, 32, 32, 3 \
  }
#define STAI_NETWORK_IN_1_SCALE_OFFSET_NUM (1)
#define STAI_NETWORK_IN_1_SCALES \
  { \
    0.00392156885936856 \
  }
#define STAI_NETWORK_IN_1_OFFSETS \
  { \
    -128 \
  }

/********************************** OUTPUTS **********************************/
#define STAI_NETWORK_OUT_NUM (1)
#define STAI_NETWORK_OUT_ALIGNMENTS \
  { \
    32 \
  }
#define STAI_NETWORK_OUT_NAMES \
  { \
    "Quantize_25_out_0" \
  }
#define STAI_NETWORK_OUT_FORMATS \
  { \
    STAI_FORMAT_S8 \
  }
#define STAI_NETWORK_OUT_SIZES \
  { \
    10 \
  }
#define STAI_NETWORK_OUT_SIZES_BYTES \
  { \
    10 \
  }

#define STAI_NETWORK_OUT_1_ALIGNMENT (32)
#define STAI_NETWORK_OUT_1_NAME "Quantize_25_out_0"
#define STAI_NETWORK_OUT_1_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_OVERRIDE)
#define STAI_NETWORK_OUT_1_FORMAT (STAI_FORMAT_S8)
#define STAI_NETWORK_OUT_1_SIZE (10)
#define STAI_NETWORK_OUT_1_SIZE_BYTES (10)
#define STAI_NETWORK_OUT_1_CHANNEL (1)
#define STAI_NETWORK_OUT_1_HEIGHT (1)
#define STAI_NETWORK_OUT_1_WIDTH (10)
#define STAI_NETWORK_OUT_1_RANK (2)
#define STAI_NETWORK_OUT_1_SHAPE \
  { \
    1, 10 \
  }
#define STAI_NETWORK_OUT_1_SCALE_OFFSET_NUM (1)
#define STAI_NETWORK_OUT_1_SCALES \
  { \
    0.00390625 \
  }
#define STAI_NETWORK_OUT_1_OFFSETS \
  { \
    -128 \
  }

/********************************** WEIGHTS **********************************/
#if LL_ATON_DBG_BUFFER_INFO_EXCLUDED == 0
#define STAI_NETWORK_WEIGHTS_NUM (9)
#define STAI_NETWORK_WEIGHTS_ALIGNMENTS \
  { \
    32, 32, 32, 32, 16, 16, 16, 32, 32 \
  }
#define STAI_NETWORK_WEIGHTS_NAMES \
  { \
    "Conv2D_3_weights", "Conv2D_8_weights", "Conv2D_13_weights", "Gemm_18_weights_transposed_3", "Gemm_21_weights_transposed_9", "Gemm_21_squeeze_y_11_148_atonn_internal_scale", "Gemm_21_squeeze_y_11_148_atonn_internal_offset", "Softmax_24_152_atonn_internal_scale", "Softmax_24_152_atonn_internal_offset" \
  }
#define STAI_NETWORK_WEIGHTS_FORMATS \
  { \
    STAI_FORMAT_S8, STAI_FORMAT_S8, STAI_FORMAT_S8, STAI_FORMAT_S8, STAI_FORMAT_S8, STAI_FORMAT_FLOAT32, STAI_FORMAT_Q7, STAI_FORMAT_FLOAT32, STAI_FORMAT_Q7 \
  }
#define STAI_NETWORK_WEIGHTS_SIZES \
  { \
    432, 4608, 18432, 4096, 640, 1, 1, 1, 1 \
  }
#define STAI_NETWORK_WEIGHTS_SIZES_BYTES \
  { \
    432, 4608, 18432, 4096, 640, 4, 1, 4, 1 \
  }

#define STAI_NETWORK_WEIGHTS_1_ALIGNMENT (32)
#define STAI_NETWORK_WEIGHTS_1_NAME "Conv2D_3_weights"
#define STAI_NETWORK_WEIGHTS_1_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_NETWORK_WEIGHTS_1_FORMAT (STAI_FORMAT_S8)
#define STAI_NETWORK_WEIGHTS_1_SIZE (432)
#define STAI_NETWORK_WEIGHTS_1_SIZE_BYTES (432)
#define STAI_NETWORK_WEIGHTS_1_CHANNEL (3)
#define STAI_NETWORK_WEIGHTS_1_HEIGHT (3)
#define STAI_NETWORK_WEIGHTS_1_WIDTH (3)
#define STAI_NETWORK_WEIGHTS_1_BATCH (3)
#define STAI_NETWORK_WEIGHTS_1_RANK (4)
#define STAI_NETWORK_WEIGHTS_1_SHAPE \
  { \
    16, 3, 3, 3 \
  }
#define STAI_NETWORK_WEIGHTS_1_SCALE_OFFSET_NUM (16)
#define STAI_NETWORK_WEIGHTS_1_SCALES \
  { \
    0.0044748461805284, 0.0027427151799202, 0.00528654875233769, 0.00324298557825387, 0.00420867837965488, 0.00342333479784429, 0.00144634756725281, 0.00390830915421247, 0.00206503318622708, 0.00293564423918724, 0.0071716895326972, 0.00153959239833057, 0.00455912109464407, 0.00254664290696383, 0.00237513636238873, 0.00244860094971955 \
  }
#define STAI_NETWORK_WEIGHTS_1_OFFSETS \
  { \
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 \
  }

#define STAI_NETWORK_WEIGHTS_2_ALIGNMENT (32)
#define STAI_NETWORK_WEIGHTS_2_NAME "Conv2D_8_weights"
#define STAI_NETWORK_WEIGHTS_2_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_HAS_BATCH)
#define STAI_NETWORK_WEIGHTS_2_FORMAT (STAI_FORMAT_S8)
#define STAI_NETWORK_WEIGHTS_2_SIZE (4608)
#define STAI_NETWORK_WEIGHTS_2_SIZE_BYTES (4608)
#define STAI_NETWORK_WEIGHTS_2_CHANNEL (16)
#define STAI_NETWORK_WEIGHTS_2_HEIGHT (3)
#define STAI_NETWORK_WEIGHTS_2_WIDTH (3)
#define STAI_NETWORK_WEIGHTS_2_BATCH (8)
#define STAI_NETWORK_WEIGHTS_2_RANK (5)
#define STAI_NETWORK_WEIGHTS_2_SHAPE \
  { \
    32, 2, 3, 3, 8 \
  }
#define STAI_NETWORK_WEIGHTS_2_SCALE_OFFSET_NUM (32)
#define STAI_NETWORK_WEIGHTS_2_SCALES \
  { \
    0.0025392509996891, 0.00344376964494586, 0.00541131198406219, 0.00225443765521049, 0.0026921103708446, 0.0082045691087842, 0.00266447081230581, 0.00366183067671955, 0.00370504334568977, 0.0029291391838342, 0.00209855637513101, 0.0022520087659359, 0.00326003832742572, 0.00334030436351895, 0.00403097737580538, 0.00272794254124165, 0.00241112732328475, 0.00710918428376317, 0.00462629459798336, 0.00234392052516341, 0.00788854341953993, 0.006156993098557, 0.00304043781943619, 0.00341267581097782, 0.00258889142423868, 0.0024462363217026, 0.00486243655905128, 0.00400244630873203, 0.00249025132507086, 0.00512684788554907, 0.00372798601165414, 0.00261896080337465 \
  }
#define STAI_NETWORK_WEIGHTS_2_OFFSETS \
  { \
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 \
  }

#define STAI_NETWORK_WEIGHTS_3_ALIGNMENT (32)
#define STAI_NETWORK_WEIGHTS_3_NAME "Conv2D_13_weights"
#define STAI_NETWORK_WEIGHTS_3_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_HAS_BATCH)
#define STAI_NETWORK_WEIGHTS_3_FORMAT (STAI_FORMAT_S8)
#define STAI_NETWORK_WEIGHTS_3_SIZE (18432)
#define STAI_NETWORK_WEIGHTS_3_SIZE_BYTES (18432)
#define STAI_NETWORK_WEIGHTS_3_CHANNEL (32)
#define STAI_NETWORK_WEIGHTS_3_HEIGHT (3)
#define STAI_NETWORK_WEIGHTS_3_WIDTH (3)
#define STAI_NETWORK_WEIGHTS_3_BATCH (8)
#define STAI_NETWORK_WEIGHTS_3_RANK (5)
#define STAI_NETWORK_WEIGHTS_3_SHAPE \
  { \
    64, 4, 3, 3, 8 \
  }
#define STAI_NETWORK_WEIGHTS_3_SCALE_OFFSET_NUM (64)
#define STAI_NETWORK_WEIGHTS_3_SCALES \
  { \
    0.00308519625104964, 0.00388265587389469, 0.00286223948933184, 0.00176120141986758, 0.00877500791102648, 0.00503010675311089, 0.00312251201830804, 0.0077988775447011, 0.00136459525674582, 0.00594074698165059, 0.00700563471764326, 0.00187744316644967, 0.00421400228515267, 0.00593042699620128, 0.00453763734549284, 0.00209668255411088, 0.00318054482340813, 0.00407297629863024, 0.00409695785492659, 0.0031968611292541, 0.00544052058830857, 0.00557793769985437, 0.0052788401953876, 0.00456516025587916, 0.00533436238765717, 0.00166415516287088, 0.0058895368129015, 0.00342853716574609, 0.00190531299449503, 0.00908474158495665, 0.00581979192793369, 0.00454224599525332, 0.00361204473301768, 0.00363350124098361, 0.00780084589496255, 0.00362940249033272, 0.000783560331910849, 0.00245054671540856, 0.00123738509137183, 0.00168729771394283, 0.00549371587112546, 0.00208677700720727, 0.0112351728603244, 0.00216082436963916, 0.00816127099096775, 0.00381820858456194, 0.00118337653111666, 0.00366037362255156, 0.00459165126085281, 0.00715451734140515, 0.00765208387747407, 0.00230961805209517, 0.00167696131393313, 0.00241474597714841, 0.00296534621156752, 0.00186238903552294, 0.00717259524390101, 0.00689423503354192, 0.00679499935358763, 0.00288984505459666, 0.00195551244542003, 0.00421215500682592, 0.0042514898814261, 0.00186417065560818 \
  }
#define STAI_NETWORK_WEIGHTS_3_OFFSETS \
  { \
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 \
  }

#define STAI_NETWORK_WEIGHTS_4_ALIGNMENT (32)
#define STAI_NETWORK_WEIGHTS_4_NAME "Gemm_18_weights_transposed_3"
#define STAI_NETWORK_WEIGHTS_4_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_NETWORK_WEIGHTS_4_FORMAT (STAI_FORMAT_S8)
#define STAI_NETWORK_WEIGHTS_4_SIZE (4096)
#define STAI_NETWORK_WEIGHTS_4_SIZE_BYTES (4096)
#define STAI_NETWORK_WEIGHTS_4_CHANNEL (64)
#define STAI_NETWORK_WEIGHTS_4_HEIGHT (1)
#define STAI_NETWORK_WEIGHTS_4_WIDTH (1)
#define STAI_NETWORK_WEIGHTS_4_BATCH (64)
#define STAI_NETWORK_WEIGHTS_4_RANK (4)
#define STAI_NETWORK_WEIGHTS_4_SHAPE \
  { \
    64, 1, 1, 64 \
  }
#define STAI_NETWORK_WEIGHTS_4_SCALE_OFFSET_NUM (64)
#define STAI_NETWORK_WEIGHTS_4_SCALES \
  { \
    0.00408888328820467, 0.00251935026608407, 0.00306309317238629, 0.00402950262650847, 0.00371521199122071, 0.00300742033869028, 0.00439287815243006, 0.00440107751637697, 0.00200598384253681, 0.00190540112089366, 0.00223615136928856, 0.00401763850823045, 0.00294473161920905, 0.00206392700783908, 0.0055667064152658, 0.00192139518912882, 0.00177012267522514, 0.00315983174368739, 0.00473549263551831, 0.00384156894870102, 0.00374408368952572, 0.00196224707178771, 0.00367320980876684, 0.00186928710900247, 0.00339233735576272, 0.00274021527729928, 0.00316008785739541, 0.00192195398267359, 0.0029208620544523, 0.00192486844025552, 0.00381379597820342, 0.00182676676195115, 0.00363689544610679, 0.00310616125352681, 0.001850800588727, 0.00291719613596797, 0.00170180841814727, 0.00206664646975696, 0.00401095021516085, 0.00181546900421381, 0.00299448356963694, 0.00173833162989467, 0.00335926143452525, 0.00267713097855449, 0.00341963185928762, 0.00181465619243681, 0.00442248536273837, 0.00394706521183252, 0.00169564154930413, 0.00351649266667664, 0.00545630464330316, 0.00428237719461322, 0.0038151852786541, 0.00173752137925476, 0.00195932551287115, 0.00348088820464909, 0.00327500957064331, 0.00378716015256941, 0.00373897142708302, 0.00345702958293259, 0.0055057262070477, 0.00169464398641139, 0.00372663210146129, 0.00193029665388167 \
  }
#define STAI_NETWORK_WEIGHTS_4_OFFSETS \
  { \
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 \
  }

#define STAI_NETWORK_WEIGHTS_5_ALIGNMENT (16)
#define STAI_NETWORK_WEIGHTS_5_NAME "Gemm_21_weights_transposed_9"
#define STAI_NETWORK_WEIGHTS_5_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_NETWORK_WEIGHTS_5_FORMAT (STAI_FORMAT_S8)
#define STAI_NETWORK_WEIGHTS_5_SIZE (640)
#define STAI_NETWORK_WEIGHTS_5_SIZE_BYTES (640)
#define STAI_NETWORK_WEIGHTS_5_CHANNEL (64)
#define STAI_NETWORK_WEIGHTS_5_HEIGHT (1)
#define STAI_NETWORK_WEIGHTS_5_WIDTH (1)
#define STAI_NETWORK_WEIGHTS_5_BATCH (64)
#define STAI_NETWORK_WEIGHTS_5_RANK (4)
#define STAI_NETWORK_WEIGHTS_5_SHAPE \
  { \
    10, 1, 1, 64 \
  }
#define STAI_NETWORK_WEIGHTS_5_SCALE_OFFSET_NUM (10)
#define STAI_NETWORK_WEIGHTS_5_SCALES \
  { \
    0.00747792236506939, 0.0058902483433485, 0.00369483814574778, 0.00460628140717745, 0.00449909642338753, 0.00341583462432027, 0.00494425045326352, 0.00396303040906787, 0.00580473756417632, 0.00460091140121222 \
  }
#define STAI_NETWORK_WEIGHTS_5_OFFSETS \
  { \
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0 \
  }

#define STAI_NETWORK_WEIGHTS_6_ALIGNMENT (16)
#define STAI_NETWORK_WEIGHTS_6_NAME "Gemm_21_squeeze_y_11_148_atonn_internal_scale"
#define STAI_NETWORK_WEIGHTS_6_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_NETWORK_WEIGHTS_6_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_NETWORK_WEIGHTS_6_SIZE (1)
#define STAI_NETWORK_WEIGHTS_6_SIZE_BYTES (4)
#define STAI_NETWORK_WEIGHTS_6_CHANNEL (1)
#define STAI_NETWORK_WEIGHTS_6_HEIGHT (1)
#define STAI_NETWORK_WEIGHTS_6_WIDTH (1)
#define STAI_NETWORK_WEIGHTS_6_RANK (1)
#define STAI_NETWORK_WEIGHTS_6_SHAPE \
  { \
    1 \
  }
#define STAI_NETWORK_WEIGHTS_6_SCALE_OFFSET_NUM (0)
#define STAI_NETWORK_WEIGHTS_6_SCALES \
  { \
  }
#define STAI_NETWORK_WEIGHTS_6_OFFSETS \
  { \
  }

#define STAI_NETWORK_WEIGHTS_7_ALIGNMENT (16)
#define STAI_NETWORK_WEIGHTS_7_NAME "Gemm_21_squeeze_y_11_148_atonn_internal_offset"
#define STAI_NETWORK_WEIGHTS_7_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_NETWORK_WEIGHTS_7_FORMAT (STAI_FORMAT_Q7)
#define STAI_NETWORK_WEIGHTS_7_SIZE (1)
#define STAI_NETWORK_WEIGHTS_7_SIZE_BYTES (1)
#define STAI_NETWORK_WEIGHTS_7_CHANNEL (1)
#define STAI_NETWORK_WEIGHTS_7_HEIGHT (1)
#define STAI_NETWORK_WEIGHTS_7_WIDTH (1)
#define STAI_NETWORK_WEIGHTS_7_RANK (1)
#define STAI_NETWORK_WEIGHTS_7_SHAPE \
  { \
    1 \
  }
#define STAI_NETWORK_WEIGHTS_7_SCALE_OFFSET_NUM (0)
#define STAI_NETWORK_WEIGHTS_7_SCALES \
  { \
  }
#define STAI_NETWORK_WEIGHTS_7_OFFSETS \
  { \
  }

#define STAI_NETWORK_WEIGHTS_8_ALIGNMENT (32)
#define STAI_NETWORK_WEIGHTS_8_NAME "Softmax_24_152_atonn_internal_scale"
#define STAI_NETWORK_WEIGHTS_8_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_NETWORK_WEIGHTS_8_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_NETWORK_WEIGHTS_8_SIZE (1)
#define STAI_NETWORK_WEIGHTS_8_SIZE_BYTES (4)
#define STAI_NETWORK_WEIGHTS_8_CHANNEL (1)
#define STAI_NETWORK_WEIGHTS_8_HEIGHT (1)
#define STAI_NETWORK_WEIGHTS_8_WIDTH (1)
#define STAI_NETWORK_WEIGHTS_8_RANK (1)
#define STAI_NETWORK_WEIGHTS_8_SHAPE \
  { \
    1 \
  }
#define STAI_NETWORK_WEIGHTS_8_SCALE_OFFSET_NUM (0)
#define STAI_NETWORK_WEIGHTS_8_SCALES \
  { \
  }
#define STAI_NETWORK_WEIGHTS_8_OFFSETS \
  { \
  }

#define STAI_NETWORK_WEIGHTS_9_ALIGNMENT (32)
#define STAI_NETWORK_WEIGHTS_9_NAME "Softmax_24_152_atonn_internal_offset"
#define STAI_NETWORK_WEIGHTS_9_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_NETWORK_WEIGHTS_9_FORMAT (STAI_FORMAT_Q7)
#define STAI_NETWORK_WEIGHTS_9_SIZE (1)
#define STAI_NETWORK_WEIGHTS_9_SIZE_BYTES (1)
#define STAI_NETWORK_WEIGHTS_9_CHANNEL (1)
#define STAI_NETWORK_WEIGHTS_9_HEIGHT (1)
#define STAI_NETWORK_WEIGHTS_9_WIDTH (1)
#define STAI_NETWORK_WEIGHTS_9_RANK (1)
#define STAI_NETWORK_WEIGHTS_9_SHAPE \
  { \
    1 \
  }
#define STAI_NETWORK_WEIGHTS_9_SCALE_OFFSET_NUM (0)
#define STAI_NETWORK_WEIGHTS_9_SCALES \
  { \
  }
#define STAI_NETWORK_WEIGHTS_9_OFFSETS \
  { \
  }
#else  // LL_ATON_DBG_BUFFER_INFO_EXCLUDED != 0
#define STAI_NETWORK_WEIGHTS_NUM (0)
#define STAI_NETWORK_WEIGHTS_ALIGNMENTS \
  { \
  }
#define STAI_NETWORK_WEIGHTS_NAMES \
  { \
  }
#define STAI_NETWORK_WEIGHTS_FORMATS \
  { \
  }
#define STAI_NETWORK_WEIGHTS_SIZES \
  { \
  }
#define STAI_NETWORK_WEIGHTS_SIZES_BYTES \
  { \
  }
#endif // LL_ATON_DBG_BUFFER_INFO_EXCLUDED != 0

/******************************** ACTIVATIONS ********************************/
#define STAI_NETWORK_ACTIVATIONS_NUM (0)
#define STAI_NETWORK_ACTIVATIONS_ALIGNMENTS \
  { \
  }
#define STAI_NETWORK_ACTIVATIONS_NAMES \
  { \
  }
#define STAI_NETWORK_ACTIVATIONS_FORMATS \
  { \
  }
#define STAI_NETWORK_ACTIVATIONS_SIZES \
  { \
  }
#define STAI_NETWORK_ACTIVATIONS_SIZES_BYTES \
  { \
  }

/****************************** NETWORK MACROS *******************************/
#if LL_ATON_DBG_BUFFER_INFO_EXCLUDED != 0
#define STAI_NETWORK_FLAGS (STAI_FLAG_INPUTS|STAI_FLAG_OUTPUTS)
#else  // LL_ATON_DBG_BUFFER_INFO_EXCLUDED == 0
#define STAI_NETWORK_FLAGS (STAI_FLAG_INPUTS|STAI_FLAG_OUTPUTS|STAI_FLAG_WEIGHTS)
#endif // LL_ATON_DBG_BUFFER_INFO_EXCLUDED == 0

#define STAI_NETWORK_ORIGIN_MODEL_NAME "mnist_cnn_32x321_PerChannel_quant_mnist_calib (1)_npz_1_OE_3_3_1"
#define STAI_NETWORK_C_MODEL_NAME "network"

/*************************** RELATIVE MEMORY POOLS ***************************/
/* no memory pools with relative addresses */

#ifdef __cplusplus
}
#endif

#endif // __STAI_ATON_NETWORK_H
