/**
  ******************************************************************************
  * @file    network_ecblobs.h
  * @brief   NN Code autogenerated DO NOT MODIFY IT
  ******************************************************************************
  * @attention
  *
  * Copyright (c) 2024 STMicroelectronics.
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  *
  ******************************************************************************
  */


#ifdef __cplusplus
extern "C" {
#endif

#include "ll_aton_caches_interface.h"

#include <string.h>

#if !defined(ECBLOB_CONST_SECTION)
#define ECBLOB_CONST_SECTION /* Empty */
#endif
#if !defined(ECBLOB_RUNTIME_SECTION)
#define ECBLOB_RUNTIME_SECTION /* Empty */
#endif

ECBLOB_CONST_SECTION
// aligned to the cache line size (equal to 64 bytes)
__attribute__((aligned(64)))
static const uint64_t _ec_blob_network_1[8] =
{
  0x00000002ca057a7aUL, 0x0000000c0000003dUL
};

#define _ec_blob_network_1_address _ec_blob_network_1

ECBLOB_CONST_SECTION
// aligned to the cache line size (equal to 64 bytes)
__attribute__((aligned(64)))
static const uint64_t _ec_blob_network_12[8] =
{
  0x00000002ca057a7aUL, 0x0000000c0000019dUL
};

#define _ec_blob_network_12_address _ec_blob_network_12

ECBLOB_CONST_SECTION
// aligned to the cache line size (equal to 64 bytes)
__attribute__((aligned(64)))
static const uint64_t _ec_blob_network_15[8] =
{
  0x00000002ca057a7aUL, 0x0000000c000001fdUL
};

#define _ec_blob_network_15_address _ec_blob_network_15

ECBLOB_CONST_SECTION
// aligned to the cache line size (equal to 64 bytes)
__attribute__((aligned(64)))
static const uint64_t _ec_blob_network_17[8] =
{
  0x00000002ca057a7aUL, 0x0000000c0000023dUL
};

#define _ec_blob_network_17_address _ec_blob_network_17

// this macro returns true if _ec_blob_network_1 blob is encrypted and must be decrypted on the fly, false otherwise
#define LL_ATON_EC_MustDecryptBlob_network__ec_blob_network_1 false

// this macro returns true if _ec_blob_network_12 blob is encrypted and must be decrypted on the fly, false otherwise
#define LL_ATON_EC_MustDecryptBlob_network__ec_blob_network_12 false

// this macro returns true if _ec_blob_network_15 blob is encrypted and must be decrypted on the fly, false otherwise
#define LL_ATON_EC_MustDecryptBlob_network__ec_blob_network_15 false

// this macro returns true if _ec_blob_network_17 blob is encrypted and must be decrypted on the fly, false otherwise
#define LL_ATON_EC_MustDecryptBlob_network__ec_blob_network_17 false

// this function MUST be called ONLY ONCE once for initializing the network
bool LL_ATON_EC_Network_Init_network(void)
{
  return true;
}

// this function should be called before each inference
bool LL_ATON_EC_Inference_Init_network(void)
{
  return true;
}

#ifdef __cplusplus
}
#endif
